// <auto-generated />
using IASquad.Poc.AzureOpenAi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IASquad.Poc.AzureOpenAi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231030103220_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");
#pragma warning restore 612, 618
        }
    }
}
